name: 'ros 1 build deb action'
author: YuuinIH
description: 'Build debian packages from ROS 1 packages using Github Action.'
input:
  ros_distro:
    description: 'The version of ros used.'
    required: false
    default: 'noetic'
  timestamp:
    description: 'Add the build timestamp behind the version number.(Just like ros buildfarm.)'
    required: false
    default: false
  workpath:
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - name: Install dependence
      run: ${{ github.action_path }}/scripts/dep.sh ${{ inputs.ros_distro }}
      shell: bash
    - name: Build and install from source
      id: build-and-install
      run: ${{ github.action_path }}/scripts/build.sh ${{ inputs.ros_distro }}
      shell: bash
    - name: Package deb
      run: ${{ github.action_path }}/scripts/package.sh ${{ inputs.ros_distro }} ${{ steps.build-and-install.outputs.catkin-ws-directory }} ${{ inputs.timestamp }}
      shell: bash
